services:
  db:
    image: postgres:16
    container_name: futcup_db
    restart: always
    environment:
      POSTGRES_USER: futcup_user
      POSTGRES_PASSWORD: futcup_pass
      POSTGRES_DB: futcup_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_URL: postgresql+psycopg2://futcup_user:futcup_pass@db:5432/futcup_db
      MIGRATE: "true"
    ports:
      - "8000:8000"

volumes:
  postgres_data:
