"""initial schema

Revision ID: 0998c86903cb
Revises: 
Create Date: 2026-03-16 18:48:26.884602

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0998c86903cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_index('idx_players_name', 'players', ['name'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('date_ini', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_tournaments_is_active', 'tournaments', ['is_active'], unique=False)
    op.create_index('idx_tournaments_name', 'tournaments', ['name'], unique=False)
    op.create_index('idx_tournaments_place', 'tournaments', ['place'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'org', 'user', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity', sa.Enum('User', 'Tournament', 'User_tournament', 'Team', 'Player', 'Player_team', 'Match', 'Event', 'Lineup', name='auditentity'), nullable=False),
    sa.Column('action', sa.Enum('Create', 'Update', 'Delete', name='auditaction'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity'], unique=False)
    op.create_index('ix_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('kit_color', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'name', name='uq_tournament_team_name')
    )
    op.create_index('idx_teams_group', 'teams', ['group'], unique=False)
    op.create_index('idx_teams_name', 'teams', ['name'], unique=False)
    op.create_index('idx_teams_tournament_id', 'teams', ['tournament_id'], unique=False)
    op.create_table('user_tournaments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'user_id', name='uq_tournament_user')
    )
    op.create_index('idx_user_tournaments_tournament_id', 'user_tournaments', ['tournament_id'], unique=False)
    op.create_index('idx_user_tournaments_user_id', 'user_tournaments', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_home_id', sa.Integer(), nullable=True),
    sa.Column('team_away_id', sa.Integer(), nullable=True),
    sa.Column('goals_home', sa.Integer(), nullable=True),
    sa.Column('goals_away', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Enum('RoundOf16', 'Quarterfinal', 'Semifinal', 'Final', name='matchround'), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Playing', 'Finished', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_away_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_home_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_matches_datetime', 'matches', ['datetime'], unique=False)
    op.create_index('idx_matches_field', 'matches', ['field'], unique=False)
    op.create_index('idx_matches_round', 'matches', ['round'], unique=False)
    op.create_index('idx_matches_status', 'matches', ['status'], unique=False)
    op.create_index('idx_matches_teams', 'matches', ['team_home_id', 'team_away_id'], unique=False)
    op.create_index('idx_matches_tournament_id', 'matches', ['tournament_id'], unique=False)
    op.create_table('player_teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'number', name='uq_team_number'),
    sa.UniqueConstraint('team_id', 'player_id', name='uq_team_player')
    )
    op.create_index('idx_player_teams_player_id', 'player_teams', ['player_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('Goal', 'Owngoal', 'Yellow', 'YellowX2', 'Red', name='eventtype'), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_event_type', 'events', ['event_type'], unique=False)
    op.create_index('idx_events_match_id', 'events', ['match_id'], unique=False)
    op.create_index('idx_events_match_player_id', 'events', ['match_id', 'player_id'], unique=False)
    op.create_index('idx_events_minute', 'events', ['minute'], unique=False)
    op.create_index('idx_events_player_id', 'events', ['player_id'], unique=False)
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('Starter', 'Bench', name='lineuprole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', 'player_id', name='uq_lineup_match_team_player')
    )
    op.create_index('idx_lineups_match_id', 'lineups', ['match_id'], unique=False)
    op.create_index('idx_lineups_match_team_id', 'lineups', ['match_id', 'team_id'], unique=False)
    op.create_index('idx_lineups_player_id', 'lineups', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lineups_player_id', table_name='lineups')
    op.drop_index('idx_lineups_match_team_id', table_name='lineups')
    op.drop_index('idx_lineups_match_id', table_name='lineups')
    op.drop_table('lineups')
    op.drop_index('idx_events_player_id', table_name='events')
    op.drop_index('idx_events_minute', table_name='events')
    op.drop_index('idx_events_match_player_id', table_name='events')
    op.drop_index('idx_events_match_id', table_name='events')
    op.drop_index('idx_events_event_type', table_name='events')
    op.drop_table('events')
    op.drop_index('idx_player_teams_player_id', table_name='player_teams')
    op.drop_table('player_teams')
    op.drop_index('idx_matches_tournament_id', table_name='matches')
    op.drop_index('idx_matches_teams', table_name='matches')
    op.drop_index('idx_matches_status', table_name='matches')
    op.drop_index('idx_matches_round', table_name='matches')
    op.drop_index('idx_matches_field', table_name='matches')
    op.drop_index('idx_matches_datetime', table_name='matches')
    op.drop_table('matches')
    op.drop_index('idx_user_tournaments_user_id', table_name='user_tournaments')
    op.drop_index('idx_user_tournaments_tournament_id', table_name='user_tournaments')
    op.drop_table('user_tournaments')
    op.drop_index('idx_teams_tournament_id', table_name='teams')
    op.drop_index('idx_teams_name', table_name='teams')
    op.drop_index('idx_teams_group', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_audit_user', table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_tournaments_place', table_name='tournaments')
    op.drop_index('idx_tournaments_name', table_name='tournaments')
    op.drop_index('idx_tournaments_is_active', table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index('idx_players_name', table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
